name = "botlist"
main = "src/index.js"
compatibility_date = "2026-09-01"
workers_dev = true
preview_urls = false

[triggers]
crons = ["*/2 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "twitchsentry-botlist"
database_id = "f8e3a83d-12f1-4010-b6f9-c421ce8af32e"

[vars]
GITHUB_REPO = "aaskjer/TwitchSentry"
GITHUB_BRANCH = "botlist"

[observability]
enabled = true
